script:
  - make

after_script:
  # The file should be created
  - if [[ ! -f "output.txt" ]]; then echo "File 'output.txt' not created "; exit 1; fi
  # After a make, all should be done
  - if [ "$(make)" != "make: Nothing to be done for 'all'." ]; then echo "second make should do nothing"; exit 1; fi

